import type { Startup } from '../types/startup'

const MOCK_STARTUPS: Startup[] = [
  {
    id: '1',
    name: 'FinCross',
    logoInitials: 'FC',
    logoColor: '#0EA5E9',
    description: 'Plataforma de pagos cross-border para pymes en LATAM con liquidación en T+0.',
    stage: 'Seed',
    sector: 'Cybersecurity',
    country: 'Colombia',
    countryCode: 'CO',
    countryFlag: '🇨🇴',
    convictionScore: 91,
    trend: 'up',
    trendValue: '+8%',
    signals: { team: 92, market: 90, traction: 93, product: 89 },
    fundingAmount: '$ 4.200.000',
    foundedYear: 2021,
    teamSize: 38,
    website: 'fincross.co',
    keySignals: [
      { id: 'ks1', text: 'MRR growth +22% MoM', type: 'positive' },
      { id: 'ks2', text: '2 ex-Nubank leads joined team', type: 'positive' },
      { id: 'ks3', text: 'Featured in Bloomberg Línea', type: 'news' },
    ],
    newsItems: [
      { id: 'n1', title: 'FinCross cierra ronda Seed de $4.2M', body: 'La ronda liderada por Kaszek permitirá la expansión a Chile y México en Q3 2024.', source: 'TechCrunch', date: '2024-03-12' },
    ],
  },
  {
    id: '2',
    name: 'Bolsillo',
    logoInitials: 'BO',
    logoColor: '#8B5CF6',
    description: 'Super-app financiera para la base de la pirámide con cuentas sin requisitos.',
    stage: 'Series A',
    sector: 'Fintech',
    country: 'Perú',
    countryCode: 'PE',
    countryFlag: '🇵🇪',
    convictionScore: 88,
    trend: 'up',
    trendValue: '+12%',
    signals: { team: 85, market: 91, traction: 88, product: 88 },
    fundingAmount: '$ 1.800.000',
    foundedYear: 2022,
    teamSize: 19,
    website: 'bolsillo.pe',
    keySignals: [
      { id: 'ks1', text: 'MRR growth +18% MoM', type: 'positive' },
      { id: 'ks2', text: '200K usuarios activos en 8 meses', type: 'positive' },
      { id: 'ks3', text: 'Alianza con Scotiabank Perú', type: 'news' },
    ],
    newsItems: [
      { id: 'n2', title: 'Bolsillo alcanza 200K usuarios activos', body: 'La fintech peruana creció 3× en usuarios desde su lanzamiento hace 8 meses.', source: 'Fintech Latam', date: '2024-03-05' },
    ],
  },
  {
    id: '3',
    name: 'MediLink',
    logoInitials: 'ML',
    logoColor: '#10B981',
    description: 'Conecta hospitales rurales con especialistas vía telemedicina asincrónica.',
    stage: 'Seed',
    sector: 'Healthtech',
    country: 'Chile',
    countryCode: 'CL',
    countryFlag: '🇨🇱',
    convictionScore: 84,
    trend: 'up',
    trendValue: '+5%',
    signals: { team: 86, market: 80, traction: 82, product: 88 },
    fundingAmount: '$ 2.200.000',
    foundedYear: 2023,
    teamSize: 9,
    website: 'medilink.cl',
    keySignals: [
      { id: 'ks1', text: 'MRR growth +18% MoM', type: 'positive' },
      { id: 'ks2', text: '3 senior hires in engineering', type: 'positive' },
      { id: 'ks3', text: 'Featured in TechCrunch LATAM', type: 'news' },
    ],
    newsItems: [
      { id: 'n3', title: 'MediLink integra 12 aseguradoras en LATAM', body: 'La integración permitirá a 4M de asegurados acceder a teleconsultas sin costo adicional.', source: 'Salud Digital', date: '2024-01-20' },
    ],
  },
  {
    id: '4',
    name: 'TalentOS',
    logoInitials: 'TO',
    logoColor: '#F59E0B',
    description: 'HR-tech para contratación y retención en empresas de rápido crecimiento.',
    stage: 'Series A',
    sector: 'HR Tech',
    country: 'México',
    countryCode: 'MX',
    countryFlag: '🇲🇽',
    convictionScore: 83,
    trend: 'up',
    trendValue: '+3%',
    signals: { team: 86, market: 80, traction: 84, product: 82 },
    fundingAmount: '$ 1.100.000',
    foundedYear: 2022,
    teamSize: 14,
    website: 'talentos.mx',
    keySignals: [
      { id: 'ks1', text: 'NPS de 72 entre empresas clientes', type: 'positive' },
      { id: 'ks2', text: 'Ex-COO de Kavak se unió al board', type: 'positive' },
      { id: 'ks3', text: 'Expansión a Colombia en Q2', type: 'news' },
    ],
    newsItems: [
      { id: 'n4', title: 'TalentOS lanza módulo de equity management', body: 'El nuevo módulo permite gestionar opciones sobre acciones para equipos distribuidos en LATAM.', source: 'StartupMX', date: '2024-02-14' },
    ],
  },
  {
    id: '5',
    name: 'Terraviva',
    logoInitials: 'TV',
    logoColor: '#22C55E',
    description: 'Agtech con sensores IoT para optimización de cultivos tropicales a escala.',
    stage: 'Pre-seed',
    sector: 'Fintech',
    country: 'México',
    countryCode: 'MX',
    countryFlag: '🇲🇽',
    convictionScore: 82,
    trend: 'neutral',
    trendValue: '0%',
    signals: { team: 84, market: 85, traction: 79, product: 80 },
    fundingAmount: '$ 3.500.000',
    foundedYear: 2020,
    teamSize: 45,
    website: 'terraviva.mx',
    keySignals: [
      { id: 'ks1', text: 'Pilotos en 1,200 hectáreas activas', type: 'positive' },
      { id: 'ks2', text: 'Pipeline estancado en Q4', type: 'negative' },
    ],
    newsItems: [],
  },
  {
    id: '6',
    name: 'DataFlow',
    logoInitials: 'DF',
    logoColor: '#439AFF',
    description: 'Plataforma de data observability para equipos de analytics en LATAM.',
    stage: 'Series A',
    sector: 'Data Analytics',
    country: 'México',
    countryCode: 'MX',
    countryFlag: '🇲🇽',
    convictionScore: 79,
    trend: 'up',
    trendValue: '+9%',
    signals: { team: 80, market: 78, traction: 81, product: 77 },
    fundingAmount: '$ 900.000',
    foundedYear: 2022,
    teamSize: 11,
    website: 'dataflow.cl',
    keySignals: [
      { id: 'ks1', text: 'ARR creció 3× en 2023', type: 'positive' },
      { id: 'ks2', text: 'Integración nativa con dbt + Snowflake', type: 'positive' },
      { id: 'ks3', text: 'Ganó concurso CORFO Startup Chile', type: 'news' },
    ],
    newsItems: [
      { id: 'n6', title: 'DataFlow gana concurso CORFO Startup Chile', body: 'El premio incluye $80K USD en equity-free funding y acceso al programa de aceleración.', source: 'El Mercurio', date: '2024-02-08' },
      { id: 'n7', title: 'Integración nativa con dbt y Snowflake', body: 'La integración reduce el tiempo de configuración de pipelines de datos de días a minutos.', source: 'Data Council', date: '2024-01-30' },
    ],
  },
  {
    id: '7',
    name: 'EduPaso',
    logoInitials: 'EP',
    logoColor: '#EC4899',
    description: 'Plataforma adaptativa de aprendizaje para educación técnica vocacional.',
    stage: 'Pre-seed',
    sector: 'EdTech',
    country: 'México',
    countryCode: 'MX',
    countryFlag: '🇲🇽',
    convictionScore: 78,
    trend: 'up',
    trendValue: '+4%',
    signals: { team: 79, market: 80, traction: 75, product: 78 },
    fundingAmount: '$ 500.000',
    foundedYear: 2023,
    teamSize: 7,
    website: 'edupaso.mx',
    keySignals: [
      { id: 'ks1', text: 'Acuerdo piloto con SEP México', type: 'positive' },
      { id: 'ks2', text: 'Retención >80% en cursos técnicos', type: 'positive' },
    ],
    newsItems: [
      { id: 'n8', title: 'EduPaso firma acuerdo piloto con SEP México', body: 'El piloto cubrirá 5,000 estudiantes de CONALEP en Jalisco y CDMX durante 2024.', source: 'EdSurge Latam', date: '2024-03-10' },
    ],
  },
  {
    id: '8',
    name: 'GreenPath',
    logoInitials: 'GP',
    logoColor: '#16A34A',
    description: 'Infraestructura de créditos de carbono verificados para empresas en LATAM.',
    stage: 'Seed',
    sector: 'ClimaTech',
    country: 'Colombia',
    countryCode: 'CO',
    countryFlag: '🇨🇴',
    convictionScore: 76,
    trend: 'up',
    trendValue: '+2%',
    signals: { team: 78, market: 77, traction: 73, product: 76 },
    fundingAmount: '$ 1.300.000',
    foundedYear: 2022,
    teamSize: 16,
    website: 'greenpath.co',
    keySignals: [
      { id: 'ks1', text: '50K créditos de carbono certificados', type: 'positive' },
      { id: 'ks2', text: 'Alianza con Gold Standard Foundation', type: 'news' },
    ],
    newsItems: [
      { id: 'n9', title: 'GreenPath certifica primeros 50K créditos de carbono', body: 'Los créditos cubren proyectos de reforestación en Amazonía colombiana verificados por Verra.', source: 'Reuters', date: '2024-01-25' },
    ],
  },
  {
    id: '9',
    name: 'AgriSight',
    logoInitials: 'AS',
    logoColor: '#84CC16',
    description: 'Visión computacional para detección temprana de plagas en cultivos andinos.',
    stage: 'Pre-seed',
    sector: 'Agro',
    country: 'Perú',
    countryCode: 'PE',
    countryFlag: '🇵🇪',
    convictionScore: 74,
    trend: 'up',
    trendValue: '+1%',
    signals: { team: 76, market: 74, traction: 72, product: 74 },
    fundingAmount: '$ 380.000',
    foundedYear: 2023,
    teamSize: 6,
    website: 'agrisight.pe',
    keySignals: [
      { id: 'ks1', text: 'Piloto activo con 200 agricultores', type: 'positive' },
      { id: 'ks2', text: 'AgriSight Secures Series A Funding', type: 'news' },
    ],
    newsItems: [
      { id: 'n10', title: 'AgriSight Secures Series A Funding', body: 'La financiación Serie A ayudará a AgriSight a expandirse a 25.000 hectáreas en los Andes.', source: 'Agro Peru', date: '2024-02-20' },
    ],
  },
  {
    id: '10',
    name: 'LogiBot',
    logoInitials: 'LB',
    logoColor: '#6366F1',
    description: 'Automatización robótica de última milla para e-commerce en ciudades medianas.',
    stage: 'Seed',
    sector: 'Logística',
    country: 'México',
    countryCode: 'MX',
    countryFlag: '🇲🇽',
    convictionScore: 72,
    trend: 'down',
    trendValue: '-3%',
    signals: { team: 74, market: 73, traction: 70, product: 71 },
    fundingAmount: '$ 1.500.000',
    foundedYear: 2021,
    teamSize: 22,
    website: 'logibot.mx',
    keySignals: [
      { id: 'ks1', text: 'Churn +15% en Q4 por competencia', type: 'negative' },
      { id: 'ks2', text: 'CAC se duplicó en últimos 6 meses', type: 'negative' },
    ],
    newsItems: [
      { id: 'n11', title: 'LogiBot enfrenta competencia de Rappi en rutas clave', body: 'Rappi Last Mile entra a 3 ciudades donde LogiBot tenía participación dominante.', source: 'Forbes MX', date: '2024-03-08' },
    ],
  },
  {
    id: '11',
    name: 'NovaMed',
    logoInitials: 'NM',
    logoColor: '#14B8A6',
    description: 'Diagnóstico asistido por IA para radiólogos en hospitales públicos de Brasil.',
    stage: 'Series A',
    sector: 'Healthtech',
    country: 'Brasil',
    countryCode: 'BR',
    countryFlag: '🇧🇷',
    convictionScore: 67,
    trend: 'down',
    trendValue: '-5%',
    signals: { team: 70, market: 68, traction: 63, product: 67 },
    fundingAmount: '$ 2.800.000',
    foundedYear: 2020,
    teamSize: 31,
    website: 'novamed.com.br',
    keySignals: [
      { id: 'ks1', text: 'Retraso de 6 meses en cert. ANVISA', type: 'negative' },
      { id: 'ks2', text: 'Competidor IBM Watson Health sale del mercado', type: 'positive' },
    ],
    newsItems: [
      { id: 'n12', title: 'NovaMed retrasa certificación ANVISA por 6 meses', body: 'La agencia regulatoria brasileña solicita estudios adicionales de validación clínica.', source: 'Health Tech BR', date: '2024-03-15' },
    ],
  },
  {
    id: '12',
    name: 'PayRural',
    logoInitials: 'PR',
    logoColor: '#F97316',
    description: 'Billetera digital para comunidades rurales no bancarizadas en Perú.',
    stage: 'Pre-seed',
    sector: 'Fintech',
    country: 'Perú',
    countryCode: 'PE',
    countryFlag: '🇵🇪',
    convictionScore: 63,
    trend: 'neutral',
    trendValue: '0%',
    signals: { team: 65, market: 66, traction: 60, product: 61 },
    fundingAmount: '$ 290.000',
    foundedYear: 2023,
    teamSize: 5,
    website: 'payrural.pe',
    keySignals: [
      { id: 'ks1', text: '1,200 usuarios en piloto inicial', type: 'positive' },
    ],
    newsItems: [],
  },
  {
    id: '13',
    name: 'Solaris',
    logoInitials: 'SO',
    logoColor: '#EAB308',
    description: 'Financiamiento y gestión de instalaciones solares residenciales en Chile.',
    stage: 'Seed',
    sector: 'EnergíaTech',
    country: 'Chile',
    countryCode: 'CL',
    countryFlag: '🇨🇱',
    convictionScore: 61,
    trend: 'down',
    trendValue: '-7%',
    signals: { team: 63, market: 62, traction: 58, product: 61 },
    fundingAmount: '$ 750.000',
    foundedYear: 2022,
    teamSize: 10,
    website: 'solaris.cl',
    keySignals: [
      { id: 'ks1', text: 'Perdió licitación MINENERGIA', type: 'negative' },
      { id: 'ks2', text: 'Tasas de financiamiento subieron 2pp', type: 'negative' },
    ],
    newsItems: [],
  },
  {
    id: '14',
    name: 'MarketLens',
    logoInitials: 'ML',
    logoColor: '#A855F7',
    description: 'Inteligencia de mercado con NLP para retail y CPG en Argentina.',
    stage: 'Pre-seed',
    sector: 'Data Analytics',
    country: 'Argentina',
    countryCode: 'AR',
    countryFlag: '🇦🇷',
    convictionScore: 58,
    trend: 'neutral',
    trendValue: '0%',
    signals: { team: 60, market: 59, traction: 55, product: 58 },
    fundingAmount: '$ 200.000',
    foundedYear: 2023,
    teamSize: 4,
    website: 'marketlens.ar',
    keySignals: [
      { id: 'ks1', text: '3 POCs activos con retailers top-10', type: 'positive' },
    ],
    newsItems: [],
  },
  {
    id: '15',
    name: 'CloudLatam',
    logoInitials: 'CL',
    logoColor: '#64748B',
    description: 'Multi-cloud management platform para medianas empresas latinoamericanas.',
    stage: 'Seed',
    sector: 'B2B SaaS',
    country: 'Colombia',
    countryCode: 'CO',
    countryFlag: '🇨🇴',
    convictionScore: 55,
    trend: 'neutral',
    trendValue: '0%',
    signals: { team: 57, market: 56, traction: 52, product: 55 },
    fundingAmount: '$ 600.000',
    foundedYear: 2022,
    teamSize: 9,
    website: 'cloudlatam.co',
    keySignals: [
      { id: 'ks1', text: 'Integración lanzada con AWS LatAm', type: 'news' },
      { id: 'ks2', text: 'Churn elevado en clientes SMB', type: 'negative' },
    ],
    newsItems: [
      { id: 'n15', title: 'CloudLatam lanza integración con AWS LatAm', body: 'La integración permite gestionar costos multi-cloud desde un único dashboard en español.', source: 'Canal TI', date: '2024-01-18' },
    ],
  },
]

export async function fetchStartups(): Promise<Startup[]> {
  return new Promise((resolve) => {
    setTimeout(() => resolve(MOCK_STARTUPS), 900)
  })
}

export const STAGE_OPTIONS   = ['Pre-seed', 'Seed', 'Series A', 'Series B']
export const SECTOR_OPTIONS  = [...new Set(MOCK_STARTUPS.map((s) => s.sector))].sort()
export const COUNTRY_OPTIONS = [...new Set(MOCK_STARTUPS.map((s) => s.country))].sort()
